### PR TITLE
new codechef solved problem added

### PR DESCRIPTION
**Pull request by Khemendra-Bhardwaj**
Hey There, I have added code for Codechef problem solution along with the problem link.
Please verify and merge it 
Thanks
Have a nice day

### CODE REVIEW

**Comment by Divyammmmmm** [comment]
Please resolve the conflict

**Review by Divyammmmmm — CHANGES_REQUESTED** [review]
please resolve conflict in your pr

**Comment by Khemendra-Bhardwaj** [comment]
hey I have resolved the conflict please verify and let me know 
Thanks

**Comment by Khemendra-Bhardwaj** [comment]
Hey can you please tell me exactly where it is showing error
In my pc there is no bug

**Pull request closed without merging**
